status:
  servername: §r§eSun Proxy§r
  playercount: 0
  maxplayers: 50
hub: localhost:19133
proxy:
  port: 19132
  xboxauthentication: true
  ipforwarding: false
  loadbalancer:
    enabled: false
    balancers:
    - hub-2.mydomain.com:19132
  statuscommand: true
  pprof:
    enabled: true
    port: 8080
  logger:
    file: sun.log
    debug: false
  motdforward: false
tcp:
  enabled: false
  key: 7pgjGVNj1aypW2v3XI5ISpIO5
